version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt update && sudo apt install -y wget gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt update
      - apt install -y terraform
      - terraform version
  build:
    commands:
#      - echo "Initializing Terraform Network Resources"
#      - cd production/network
#      - terraform init
#      - echo "Validating Terraform configuration..."
#      - terraform validate
#      - echo "Planning Terraform changes..."
#      - terraform plan -out=tfplan
#      - echo "Applying Terraform changes..."
#      - terraform apply tfplan
#      - cd ../../
#      - echo "Initializing Terraform Common Resources"
#      - cd production/common
#      - terraform init
#      - echo "Validating Terraform configuration..."
#      - terraform validate
#      - echo "Planning Terraform changes..."
#      - terraform plan -out=tfplan
#      - echo "Applying Terraform changes..."
#      - terraform apply tfplan
#      - cd ../../
#      - echo "[+] Initializing Terraform Ezedox Resources"
#      - cd production/ezedox
#      - aws s3 cp s3://bp-sg-prod-elbs-binaries/bp-sg-prod-ezedox-values/ezedox_bs.yaml .
#      - terraform init
#      - echo "[+] Validating Terraform configuration..."
#      - terraform validate
#      - echo "[+] Planning Terraform changes..."
#      - terraform plan -out=tfplan
#      - echo "[+] Applying Terraform changes..."
#      - terraform apply tfplan
#      - cd ../../
#      - echo "Initializing Terraform Oustlabs Resources"
#      - cd production/oustlabs
#      - aws s3 cp s3://bp-tf-statefile-bucket/values/frankfurt/oustlabs_bs.yaml .
#      - terraform init
#      - echo "Validating Terraform configuration..."
#      - terraform validate
#      - echo "Planning Terraform changes..."
#      - terraform plan -out=tfplan
#      - echo "Applying Terraform changes..."
#      - terraform apply tfplan
##      - cd ../../
      - echo "[+] Initializing Terraform hrms Resources"
      - cd production/hrms
      - terraform init
      - echo "[+] Validating Terraform configuration..."
      - terraform validate
      - echo "[+] Planning Terraform changes..."
      - terraform plan -out=tfplan
      - echo "[+] Applying Terraform changes..."
      - terraform apply tfplan
#      - cd ../../
#      - echo "[+] Initializing Terraform Bastion Resources"
#      - cd production/bastion
#      - terraform init
#      - echo "[+] Validating Terraform configuration..."
#      - terraform validate
#      - echo "[+] Planning Terraform changes..."
#      - terraform plan -out=tfplan
#      - echo "[+] Applying Terraform changes..."
#      - terraform apply tfplan
#      - echo "[+] Initializing Terraform ElasticSearch Resources"
#      - cd production/elasticsearch
#      - terraform init
#      - echo "[+] Validating Terraform configuration..."
#      - terraform validate
#      - echo "[+] Planning Terraform changes..."
#      - terraform plan -out=tfplan
#      - echo "[+] Applying Terraform changes..."
#      - terraform apply tfplan
#      - echo "[+] Initializing Terraform Landing Resources"
#      - cd production/landing
#      - terraform init
#      - echo "[+] Validating Terraform configuration..."
#      - terraform validate
#      - echo "[+] Planning Terraform changes..."
#      - terraform plan -out=tfplan
#      - echo "[+] Applying Terraform changes..."
#      - terraform apply tfplan
  post_build:
    commands:
      - echo "Deployment Successful Frankfurt"